### ISSUE TITLE
A release with constraintskinds fix?

### ISSUE THREAD

**Issue by phadej** [diagrams/diagrams-core#102]
Could the (patch) release be made with that fix?

I made a revision for 1.4.1 so there aren't an install plan lens-4.16 and diagrams-1.4 for GHC-7.8/7.6 now. (other diagrams-core-1.4 versions have lens <4.16).

**Comment by phadej** [comment]
- https://matrix.hackage.haskell.org/package/diagrams-core matrix
- https://hackage.haskell.org/package/diagrams-core-1.4.1/revisions/ revision

**Comment by byorgey** [comment]
Thanks, I wasn't aware of this issue.  I'll try to put out a release soon, though I'm going to be on vacation for the rest of the week.

**Comment by byorgey** [comment]
Released `diagrams-core-1.4.1.1` with the fixes.
