### ISSUE TITLE
New release on Hackage to allow GHC 8.8.1

### ISSUE THREAD

**Issue by wismill** [diagrams/diagrams-core#107]
Hello, could you upload a new release on Hackage to be able to compile the `diagrams-*` libraries with GHC 8.8.1?
Thanks for the great work!

**Comment by byorgey** [comment]
Thanks, apologies for the radio silence here. I'm currently working through a big backlog of upper bounds bumps etc., hopefully within the next few days everything in the diagrams ecosystem should be updated for GHC 8.8.

**Comment by byorgey** [comment]
Uploaded `diagrams-core-1.4.2`.
