### ISSUE TITLE
Is it possible to serialize a diagram to a file and then render it with another program, another time?

### ISSUE THREAD

**Issue by kindaro** [diagrams/diagrams-core#109]
I defined some unique diagram and I want to show it to a friend. If I rasterize _(or vectorize)_ it, it will inevitably lose some of its wondrous qualities. I see that a diagram is a [complicated data type][2], so I am not sure how to go about this task.

[2]: https://hackage.haskell.org/package/diagrams-core-1.4.1.1/docs/src/Diagrams.Core.Types.html#QDiagram

**Comment by fryguybob** [comment]
Diagrams programs can be distributed as source or as a binary.  We do not make any attempt to abstract away from diagrams being programs.

That said, it would be nice to package a diagrams program as, say, a webpage with javascript.

**Comment by kindaro** [comment]
@fryguybob So my best option is to create a shared object file that someone else can link to? Can you advise me how best to go about it?

**Comment by fryguybob** [comment]
I would need much more context to know what would be best for you.  Personally a shared object file is one of the last options I would tend to need, though it is possible to do.  More common for my purposes are distributing as source to be built as either a library or an executable.  Another option that I would use in the right context would be distributing as an executable that takes command line options as the interface for generating a specific diagram.  We have a tutorial for that here:

https://archives.haskell.org/projects.haskell.org/diagrams/doc/cmdline.html

**Comment by kindaro** [comment]
Thank you, I think I understand the situation now.
