### ISSUE TITLE
diagrams-core introduced breaking change in a patch version

### ISSUE THREAD

**Issue by phadej** [diagrams/diagrams-core#110]
Between 1.4.1 and 1.4.1.1 

```diff
+class (Floating s, Ord s) => OrderedField s
+instance (Floating s, Ord s) => OrderedField s
- type OrderedField s = (Floating s, Ord s)
```

This is breaking change, not only because old GHC are picky (need `ConstraintKinds`, sometimes `UndecidableInstances` to use these),

But also because type synonyms cannot be partially applied.

```haskell
data Dict c a where
   Dict :: c a -> Dict

-- this can be written with class, but not with type synonym:
dict :: Dict OrderedField Double
dict = Dict
```

There's nothing one can do anymore, but please be careful when you do what feels to be "internal refactoring"

**Comment by byorgey** [comment]
Ouch, thanks for pointing this out!  I don't remember but I think this was definitely a case of not noticing that change went into the patch version.  Is there anything we can do to mitigate the damage?

**Comment by phadej** [comment]
1.4.1.1 was released so long ago, there isn't any big damage, except some older `diagrams-` packages.

I made revisions for affected `diagrams-lib` and looking at few others.

I also opened a bunch of PRs (as you may noticed), relaxing bounds and fixing some small issues:

With those changes the following packages HEADs build against each other as conditionals specify the GHCs. I tried to keep lower bounds as relaxed as I could, but if you generally dropping GHC-7.8 support, it will be easier to drop it for all `diagrams-*` family at once.

(Note: builds with GHC-8.8 too, but I haven't run any tests locally)

```
if impl(ghc >= 7.4)
  packages:
      force-layout
    , monoid-extras
    , statestack
    , svg-builder

if impl(ghc >= 7.6)
  packages:
    dual-tree

if impl(ghc >= 7.8)
  packages:
      SVGFonts
    , diagrams-postscript
    , diagrams-solve
    , diagrams-svg
    , diagrams-core

if impl(ghc >= 7.10)
  packages:
      diagrams
    , diagrams-lib
    , diagrams-contrib
```

**Comment by byorgey** [comment]
Yeah, we are currently dropping support for anything prior to GHC 7.10.  So all those ifs should not be necessary.

**Comment by phadej** [comment]
@byorgey please remember to bump `base` lower bounds when you drop support for older GHCs. The metadata is what tells tools and people (e.g. hackage trustees) when something should be ok or not.

In my PRs I left it as low as I could.

**Comment by byorgey** [comment]
Will try to keep that in mind, thanks for the reminder.
