### ISSUE TITLE
Support monoid-extras 0.6 and future versions of base (Option deprecation)

### ISSUE THREAD

**Issue by sternenseemann** [diagrams/diagrams-core#115]
Seems like the `Option` type will be deprecated and replaced by `Maybe`. This seems easy enough to fix, in fact `monoid-extras` 0.6 already has done that, but it probably needs some consideration as it affects the public API as far as I understand it.

**Comment by byorgey** [comment]
Yes, there is already a PR for that, actually: https://github.com/diagrams/diagrams-core/pull/114 .  It will be updated soon.

**Comment by byorgey** [comment]
#114 is now merged, so closing this.  A new version of `diagrams-core` should be uploaded to Hackage soon (once CI passes), and I will continue working on updating the rest of the downstream packages.
