### ISSUE TITLE
Doesn't work with old monoid-extras

### ISSUE THREAD

**Issue by brandon-leapyear** [diagrams/diagrams-core#116]
diagrams-core-1.5.0 replaces Option with Maybe, but still claims compatibility with monoid-extras < 0.6. Either the lower bound of `monoid-extras` should be bumped up in `diagrams-core.cabal` or diagrams-core should maintain Option compatibility

**Comment by byorgey** [comment]
Ah, thanks for the report, you're absolutely right.  I'll look into this in the next couple days.
