### ISSUE TITLE
"Grouping" for transparent things

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-core#21]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=80>. Original issue from byor...@gmail.com on April 16, 2012, 02:05:29 PM UTC)

cairo and SVG both support a notion of &quot;grouping&quot; so that grouped things will have their transparency set as a group -- i.e. as if everything were drawn first and then the resulting bitmap made transparent.  It would be nice if diagrams supported this as well, though it's not entirely obvious how this should work.  At a minimum we need to work out how to expose more tree structure to backends first.

**Comment by cchalmers** [comment]
This was done with bafcf89. Currently the pgf and svg backends implement it.
