### ISSUE TITLE
Generic conversion from matrices to Transformations

### ISSUE THREAD

**Issue by byorgey** [diagrams/diagrams-core#40]
For completeness' sake it might be nice to add a function to `Diagrams.Core.Transform` which converts from a "matrix" (probably a list of vectors, one for each basis element, + a vector for the translation component) to a `Transformation`.  Note, however, this requires being able to perform general matrix inversion.  Perhaps we could use http://hackage.haskell.org/package/bed-and-breakfast, not sure how many new dependencies that would pull in.

**Comment by cchalmers** [comment]
This was done in diagrams/diagrams-lib@95cd10c.
