### ISSUE TITLE
New release for 7.10

### ISSUE THREAD

**Issue by edsko** [diagrams/diagrams-core#83]
Any chance of a Hackage release with 7.10 compatibility? We need new releases of

* diagrams-cairo
* diagrams-contrib
* diagrams-core 
* diagrams-lib
* diagrams-solve
* SVGFonts

as well as

* active
* dual-tree
* force-layout
* monoid-extras
* statestack

And moreover the upper bound on `lens` needs to be relaxed to allow for version 4.9.

**Comment by byorgey** [comment]
We are hard at work on a major new 1.3 release, which should be out very soon and include support for GHC 7.10 and lens 4.9.  After that we can look into the possibility of point releases in the 1.2 series adding support for GHC 7.10, so folks who aren't yet ready to upgrade to 1.3 can still use diagrams on GHC 7.10, though off the top of my head I don't know how much work that would be.

**Comment by edsko** [comment]
Ok, great! Looking forward to it :)

**Comment by bergey** [comment]
I *thought* I had uploaded 1.2.* versions of everything allowing `lens-4.9`.  I see I missed at least `diagrams-cairo`.  I think I have the code locally, and just need to upload it.

`base-4.8` is a little more work, though most of the work for `diagrams-1.3` was to get it building with `-Wall -Werror`.
