### ISSUE TITLE
Document (Transformable (Envelope ...)) instance

### ISSUE THREAD

**Issue by hanshoglund** [diagrams/diagrams-core#89]
I've been trying to understand the inner workings of `diagrams-core` when I ran into this nugget ;)

https://github.com/diagrams/diagrams-core/blob/1e9e2cc3660af3fab2254777f958ebf06e8215b8/src/Diagrams/Core/Envelope.hs#L157

Any possibility @byorgey, @cchalmers or someone else could elaborate on how this works?

**Comment by byorgey** [comment]
Haha, yes, I wrote that code many years ago, and I remember writing that comment.  I think I can reconstruct how it works.  I'll try to document it soon.

**Comment by byorgey** [comment]
I finally got around to this.  Hope this is helpful!
